### ISSUE TITLE
Performance vs. msgpack-lite?

### ISSUE THREAD

**Issue by Zentendo** [tsne/msgpack-js#1]
Hi, I was wondering about what the performance was like vs. msgpack-lite? 

https://github.com/kawanet/msgpack-lite

**Comment by tsne** [comment]
Hi @Zentendo,

to be honest, I've not tested the performance of this library, but I guess it is not as fast as `msgpack-lite`. `messagepack` was not written with performance in mind, but should fit the needs of [mprot](https://github.com/mprot/mprot). This means, it should be fairly small and should provide a good level of type safety.
